### ISSUE TITLE
 CoverTemplate has changed

### ISSUE THREAD

**Issue by Clam58** [pfandrade/ha-custom-components#2]
Error when using this component with  core-2022.2.x.
The logging shows:

File "/config/custom_components/pcc/cover.py", line 152, in __init__
    super().__init__(
TypeError: __init__() missing 1 required positional argument: 'hass'

I’ve checked the current version of the CoverTemplate component was based on (https://github.com/home-assistant/core/blob/dev/homeassistant/components/template/cover.py) and it does indeed pass a hass object as a 1st argument. 

With this change the error clears and the component works.

Here is the call with the extra parameter 

super().__init__(
            hass,
            availability_template=availability_template,
            icon_template=icon_template,
            entity_picture_template=entity_picture_template,
        )

Hope you get a chance to review this, and if you agree, update the code accordingly.

Thanks

**Comment by marcodallago** [comment]
Thanks man! It works now, please, i suggest you to make a pull request in order to implement it.

Unfortunately I still have issue with the cover itself. Could you kindly explain me how you set it up? You just added the custom cover in configuration? could you please share it?

Mine, I don't know why, does not toggle switch on/off

**Comment by pfandrade** [comment]
I've updated the code to support the latest version. Thanks
